exclude: [CONTRIBUTING.md, Gemfile, Gemfile.lock, LICENSE, README.md, script, vendor]
plugins:
  - jekyll-analytics
jekyll_analytics:
  Matomo:
    url: matomo.ddavo.me
    siteId: "2"
collections:
  pages:
    output: true
    permalink: /:categories/:title:output_ext
